### ISSUE TITLE
Can't access the linked question if I'm not logged in before

### ISSUE THREAD

**Issue by louckousse** [Zenika/FAQ#169] opened 2019-02-07 09:22 UTC
After clicking on a link to a specific question, I except to land on the right question even if I need to log.

At this moment, after logging in I am redirected to the home page instead of the page I actually want.

**Comment by Errorname** [comment] 2019-02-07 10:11
This seems to be a recurring issue, but I can't reproduce it and it's driving me crazy!

Are you able to reproduce it 100%? If so, can you give me exactly the steps you do to reproduce it?

Thanks 🙏

**Comment by Errorname** [comment] 2019-02-20 17:25
I rewrote the auth service, this *should* have been fixed. I'll close this issue but don't hesitate to re-open it if you think its still there

**Closed by Errorname** 2019-02-20 17:25 UTC
Labels: bug, help wanted, priority/high
