### ISSUE TITLE
Error after submitting an answer to a brand new question

### ISSUE THREAD

**Issue by hgwood** [Zenika/FAQ#56] opened 2018-04-12 14:10 UTC
![image](https://user-images.githubusercontent.com/1656170/38682688-03f8ef3e-3e6c-11e8-8988-587ebd4b445d.png)

After clicking OK the page went blank. I reloaded and that took me back to editing the answer. I clicked submit again and this time it worked. Might be hard to reproduce :/

**Comment by Errorname** [comment] 2018-04-12 14:16
Thanks for the issue. I encountered this bug, but couldn't reproduce it after refreshing my cache.

I'm gonna close this issue, but I can reopen it if you can give steps to consistently reproduce this bug.

**Closed by Errorname** 2018-04-12 14:16 UTC

**Comment by hgwood** [comment] 2018-04-23 13:33
I suspect this might happen when connectivity is lost. I need to confirm.
